### ISSUE TITLE
[bug]DISCORDSRV support

### ISSUE THREAD

**Issue by vincentwang0905** [LOOHP/InteractiveChat-DiscordSRV-Addon#10]
```
[21:37:51 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/events/message/MessageReceivedEvent
        at InteractiveChatDiscordSrvAddon-4.0.3.10.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents$JDAEvents.onMessageReceived(OutboundToDiscordEvents.java:737)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:482)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by xamionex** [comment]
bump

found any fix/workaround?

**Comment by loohpjames** [comment]
Are you sure your DiscordSRV started correctly without any problems?

**Comment by LOOHP** [comment]
Are you sure your DiscordSRV started correctly without any problems?

**Comment by xamionex** [comment]
> Are you sure your DiscordSRV started correctly without any problems?

Sorry! It apparently didn't launch the newest version for some reason, It's working now thank you!
