### ISSUE TITLE
1.18 Console spam

### ISSUE THREAD

**Issue by andy3559167** [LOOHP/InteractiveChat-DiscordSRV-Addon#11]
[03:18:24 ERROR]: [DiscordSRV] DiscordSRV API Listener com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents 發生錯誤
[03:18:24 ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 50001: Missing Access
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[03:18:24 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.4.7.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.reload(DiscordCommands.java:99)
[03:18:24 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.4.7.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.<init>(DiscordCommands.java:90)
[03:18:24 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.4.7.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.ready(DiscordReadyEvents.java:45)
[03:18:24 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.4.7.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.onDiscordReady(DiscordReadyEvents.java:35)
[03:18:24 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:18:24 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03:18:24 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:18:24 ERROR]: [DiscordSRV]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:136)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:1347)
[03:18:24 ERROR]: [DiscordSRV]  at java.base/java.lang.Thread.run(Thread.java:833)
[03:18:24 ERROR]: [DiscordSRV] Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[03:18:24 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[03:18:24 ERROR]: [DiscordSRV]  ... 12 more

**Comment by andy3559167** [comment]
The function is normal, but this message will appear on the console when starting up.

**Comment by LOOHP** [comment]
You did to give slash command access to your discordbot via the discord dev application. Reinvite your bot afterwards.

**Comment by andy3559167** [comment]
[04:47:48 ERROR]: Error occurred while enabling InteractiveChatDiscordSrvAddon v4.0.4.7 (Is it up to date?)
github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 50001: Missing Access
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[DiscordSRV-Build-1.24.0.jar:?]
        at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633) ~[DiscordSRV-Build-1.24.0.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.reload(DiscordCommands.java:99) ~[InteractiveChatDiscordSrvAddon-4.0.4.7.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.<init>(DiscordCommands.java:90) ~[InteractiveChatDiscordSrvAddon-4.0.4.7.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.ready(DiscordReadyEvents.java:45) ~[InteractiveChatDiscordSrvAddon-4.0.4.7.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.<init>(DiscordReadyEvents.java:27) ~[InteractiveChatDiscordSrvAddon-4.0.4.7.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.onEnable(InteractiveChatDiscordSrvAddon.java:210) ~[InteractiveChatDiscordSrvAddon-4.0.4.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-27]        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
        at github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[DiscordSRV-Build-1.24.0.jar:?]
        at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71) ~[DiscordSRV-Build-1.24.0.jar:?]
        at github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36) ~[DiscordSRV-Build-1.24.0.jar:?]
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[DiscordSRV-Build-1.24.0.jar:?]
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[DiscordSRV-Build-1.24.0.jar:?]
        ... 17 more
[04:47:48 INFO]: [InteractiveChatDiscordSRVAddon] Disabling InteractiveChatDiscordSrvAddon v4.0.4.7
[04:47:48 INFO]: [ICDiscordSrvAddon] InteractiveChat DiscordSRV Addon has been Disabled!

**Comment by andy3559167** [comment]
I got an error after I re-invited the robot. :(

**Comment by andy3559167** [comment]
[04:49:27 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at InteractiveChatDiscordSrvAddon-4.0.4.7.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents$JDAEvents.onMessageReceived(OutboundToDiscordEvents.java:737)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:482)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by LOOHP** [comment]
Can you show me your entire latest.log containing this error?

**Comment by andy3559167** [comment]
[2021-12-09-3.log](https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/files/7682371/2021-12-09-3.log)
An error occurs when discordsrv enters the bot token
Normal use of version 1.17.1

**Comment by LOOHP** [comment]
```
[06:06:14] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 50001: Missing Access
```
You still haven't given your bot slash command access. Take a look at the Q&A section of InteractiveChat DiscordSRV Addon's spigotmc resource page.

**Comment by andy3559167** [comment]
I give the robot administrator permissions. I thought it included slash command access permission. Sorry for the trouble, but after I installed all the plug-ins, doscordsrv still has related error codes.

**Comment by andy3559167** [comment]
[latest.log](https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/files/7685117/latest.log)
At time [20:32:40] discordsrv reported an error about InteractiveChat DiscordSRV Addon.
