### ISSUE TITLE
 Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "source" is null

### ISSUE THREAD

**Issue by Spiderjockey02** [LOOHP/InteractiveChat-DiscordSRV-Addon#13]
```
[16:24:48] [JDA MainWS-ReadThread/WARN]: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "source" is null
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at InteractiveChatDiscordSrvAddon-4.1.0.3.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageUtils.copyImage(ImageUtils.java:284)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at InteractiveChatDiscordSrvAddon-4.1.0.3.jar//com.loohp.interactivechatdiscordsrvaddon.resource.ModelRender$RenderResult.getImage(ModelRender.java:266)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at InteractiveChatDiscordSrvAddon-4.1.0.3.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.onSlashCommand(DiscordCommands.java:263)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:482)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[16:24:48] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```
Server version: paper 1.17
Plugins version (latest updated a couple hours ago)

**Comment by LOOHP** [comment]
Try updating to the latest dev build (4.1.0.21) as of now and do `/icd reloadtexture --redownload`

Remember to update InteractiveChat as well.
