### ISSUE TITLE
InteractiveChatDiscordSrvAddon v4.1.1.9 generated an exception while executing task 278

### ISSUE THREAD

**Issue by Futodama** [LOOHP/InteractiveChat-DiscordSRV-Addon#15]
[00:39:15 WARN]: [InteractiveChatDiscordSRVAddon] Plugin InteractiveChatDiscordSrvAddon v4.1.1.9 generated an exception while executing task 278
java.lang.NoClassDefFoundError: com/loohp/interactivechat/objectholders/ICPlayerFactory
        at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$onEnable$0(InteractiveChatDiscordSrvAddon.java:272) ~[InteractiveChatDiscordSrvAddon-4.1.1.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-152]        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-152]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.loohp.interactivechat.objectholders.ICPlayerFactory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        
        
        He is constantly spamming this message. Please fix that!

**Comment by LOOHP** [comment]
You need to update InteractiveChat and InteractiveChatDiscordSRVAddon at the same time. they need to work with each other.
Try updating them both to the latest (4.1.1.10 as of now)
