### ISSUE TITLE
Embed Wasnt Send 

### ISSUE THREAD

**Issue by NixonSiagian** [LOOHP/InteractiveChat-DiscordSRV-Addon#18]
[04:17:14 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at InteractiveChatDiscordSrvAddon-4.1.4.13.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents$JDAEvents.onMessageReceived(OutboundToDiscordEvents.java:810)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at DiscordSRV-Build-1.26.0-SNAPSHOT-58ab62b.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by LOOHP** [comment]
This error should be caused by an earlier error.
