### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.loohp.interactivechatdiscordsrvaddon.resources.ResourceManager.getTextureManager()" because the return value of "java.util.function.Supplier.get()" is null

### ISSUE THREAD

**Issue by sticks-stuff** [LOOHP/InteractiveChat-DiscordSRV-Addon#20]
whenever using a command from discord or using [inv] i get this error

i also get 
`java.lang.NullPointerException: Cannot invoke "com.loohp.interactivechatdiscordsrvaddon.resources.ResourceManager.getLanguageManager()" because "manager" is null` whenever /playerlist is used too

**Comment by sticks-stuff** [comment]
oh hey this might be useful too

```[01:50:49 INFO]: UwU_catgirl issued server command: /icd status
[01:50:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'icd' in plugin InteractiveChatDiscordSrvAddon v4.2.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.loohp.interactivechatdiscordsrvaddon.resources.ResourceManager.getResourcePackInfo()" because "com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.plugin.resourceManager" is null
        at com.loohp.interactivechatdiscordsrvaddon.Commands.onCommand(Commands.java:73) ~[InteractiveChatDiscordSrvAddon-4.2.2.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more```

**Comment by sticks-stuff** [comment]
and this (appears on startup)
```[01:34:09 WARN]: [InteractiveChatDiscordSRVAddon] Plugin InteractiveChatDiscordSrvAddon v4.2.2.0 generated an exception while executing task 26
java.lang.NoSuchMethodError: 'boolean com.loohp.interactivechat.utils.JsonUtils.isValid(java.lang.String)'
        at com.loohp.interactivechatdiscordsrvaddon.resources.ResourceManager.loadResources(ResourceManager.java:153) ~[InteractiveChatDiscordSrvAddon-4.2.2.0.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$reloadTextures$15(InteractiveChatDiscordSrvAddon.java:636) ~[InteractiveChatDiscordSrvAddon-4.2.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-39]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```
