### ISSUE TITLE
[InteractiveChatDiscordSRVAddon] java.lang.NoSuchMethodError: 'github.scarsz.discordsrv.api.SlashCommandManager github.scarsz.discordsrv.api.ApiManager.getSlashCommandManager()'

### ISSUE THREAD

**Issue by Slime1207** [LOOHP/InteractiveChat-DiscordSRV-Addon#22]
Hello , can you solve my ploblum ?
Permission given (application.command and bot adminn

Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] java.lang.NoSuchMethodError: 'github.scarsz.discordsrv.api.SlashCommandManager github.scarsz.discordsrv.api.ApiManager.getSlashCommandManager()'
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at InteractiveChatDiscordSrvAddon-4.2.2.6.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.reload(DiscordCommands.java:501)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at InteractiveChatDiscordSrvAddon-4.2.2.6.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.<init>(DiscordCommands.java:484)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at InteractiveChatDiscordSrvAddon-4.2.2.6.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.ready(DiscordReadyEvents.java:62)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at InteractiveChatDiscordSrvAddon-4.2.2.6.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.onDiscordReady(DiscordReadyEvents.java:53)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at DiscordSRV-Build-1.25.1.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:138)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at DiscordSRV-Build-1.25.1.jar//github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:1381)
[07:04:38] [DiscordSRV - Initialization/ERROR]: [InteractiveChatDiscordSRVAddon] 	at java.base/java.lang.Thread.run(Thread.java:833)

For plugins version , both is 4.2.2.6
Please reply soom

**Comment by LOOHP** [comment]
Update to the latest dev build of DiscordSRV
