### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by FurnyGo** [LOOHP/InteractiveChat-DiscordSRV-Addon#24]
I use a system of webhooks, but this addon apparently does not want to convert them.
```[10:29:17 WARN]: [InteractiveChatDiscordSRVAddon] Plugin InteractiveChatDiscordSrvAddon v4.2.3.0 generated an exception while executing task 734
java.lang.NoSuchMethodError: 'void github.scarsz.discordsrv.util.WebhookUtil.editMessage(github.scarsz.discordsrv.dependencies.jda.api.entities.TextChannel, java.lang.String, java.lang.String, java.util.Collection)'
        at com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents$JDAEvents.lambda$onMessageReceived$0(OutboundToDiscordEvents.java:877) ~[InteractiveChatDiscordSrvAddon-4.2.3.0 (1).jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1760]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1760]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LOOHP** [comment]
Make sure you are using the latest DEV build of DiscordSRV

**Comment by FurnyGo** [comment]
fixed in dev build
