### ISSUE TITLE
GuildSlashCommandUpdateEvent

### ISSUE THREAD

**Issue by Futodama** [LOOHP/InteractiveChat-DiscordSRV-Addon#25]
[14:59:49 INFO]: [InteractiveChatDiscordSRVAddon] Loading InteractiveChatDiscordSrvAddon v4.2.3.2
[14:59:49 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] github/scarsz/discordsrv/api/events/GuildSlashCommandUpdateEvent initializing InteractiveChatDiscordSrvAddon v4.2.3.2 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/api/events/GuildSlashCommandUpdateEvent
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3434) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3459) ~[?:?]
        at java.lang.Class.getMethods(Class.java:2051) ~[?:?]
        at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:90) ~[DiscordSRV-Build-1.25.1.jar:?]
        at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.onLoad(InteractiveChatDiscordSrvAddon.java:252) ~[InteractiveChatDiscordSrvAddon-4.2.3.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.api.events.GuildSlashCommandUpdateEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 11 more

**Comment by LOOHP** [comment]
Update discordsrv to the latest snapshot
