### ISSUE TITLE
InteractionFailureException when using [inv] [ender] [i] in chat

### ISSUE THREAD

**Issue by tygh78071388** [LOOHP/InteractiveChat-DiscordSRV-Addon#31]
請原諒我使用中文 我想這樣會比較好表達我遇到的問題

當我使用展示指令如[inv] [end] 或[i]展示的是界伏盒或書本時 在ICD的改版後 可以讓玩家於DC中直接選擇某一個物品的內容 在當時改版時似乎沒有問題遇到問題 但後續ICD更新後就出現了下面的(1)錯誤代碼

產生下面的(1)錯誤代碼的方式為 玩家於伺服器某分流展示上述可以選擇的物品時，使用Discord進行物品的選擇，點選後就會產生(1)錯誤代碼並且機器人會提示說"此選項已過期" 有時又會正常顯示 有時又會顯示錯誤 並且其他伺服器分流會同時顯示
"[DiscordSRV] DiscordSRV encountered an unknown Discord error: 10062: Unknown interaction" 這一段

試過更新IC 和 ICD 以及 DiscordSRV到最新版本 但無法解決
InteractiveChat version: 4.2.5.7
ICDiscordSRVAddon version: 4.2.5.7
DiscordSRV-Build-1.26.1
Paper version git-Paper-279 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a7df847)

補充:我們共有四個分流 並且機器人都是設定為同一個

(1)
```
[DiscordSRV] DiscordSRV encountered an unknown exception: Cascading failure caused by interaction callback failure
github.scarsz.discordsrv.dependencies.jda.api.exceptions.InteractionFailureException: Cascading failure caused by interaction callback failure
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.restaction.interactions.InteractionCallbackActionImpl.handleResponse(InteractionCallbackActionImpl.java:84)
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.handleResponse(Request.java:259)
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:237)
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:141)
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:124)
	at DiscordSRV-Build-1.26.1.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LOOHP** [comment]
"我們共有四個分流 並且機器人都是設定為同一個"

DiscordSRV does not support sharing the same bot across multiple instances (servers).

**Comment by tygh78071388** [comment]
> "我們共有四個分流 並且機器人都是設定為同一個"
> 
> DiscordSRV does not support sharing the same bot across multiple instances (servers).

Oh no.. 這個有方法解決嗎? 如果真的沒有的話 我會嘗試將其猜分  不好意思打擾了

**Comment by LOOHP** [comment]
You should always use separate bots for each instance (server).
