### ISSUE TITLE
Unable to retrieve data. (-11) when using /inv

### ISSUE THREAD

**Issue by sub-kek** [LOOHP/InteractiveChat-DiscordSRV-Addon#37]
After updating the plugin, players started complaining to me. I found stacktrace.

`java.lang.ExceptionInInitializerError
       at com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getFullBodyImage(ImageGeneration.java:544)
       at com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getPlayerInventoryImage(ImageGeneration.java:445)
       at com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getPlayerInventoryImage(ImageGeneration.java:320)
       at com.loohp.interactivechatdiscordsrvaddon.utils.DiscordContentUtils.createContents(DiscordContentUtils.java:227)
       at com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.onSlashCommand(DiscordCommands.java:1023)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
       at github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344)
       at github.scarsz.discordsrv.api.ApiManager.handleSlashCommandEvent(ApiManager.java:319)
       at github.scarsz.discordsrv.api.ApiManager.onSlashCommand(ApiManager.java:293)
       at github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
       at github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
       at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
       at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
       at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
       at github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
       at github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
       at github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
       at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
       at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.util.NoSuchElementException: No value present
       at java.base/java.util.Optional.get(Optional.java:143)
       at com.loohp.interactivechatdiscordsrvaddon.utils.ArmorUtils.<clinit>(ArmorUtils.java:70)
       ... 31 more`

**Comment by LOOHP** [comment]
Which version of Minecraft is your server on?

**Comment by sub-kek** [comment]
1.16.5 purpur

**Comment by LOOHP** [comment]
Feel free to give build #300 on the build server a try to see whether the issue is fixed.

**Comment by 123yuyu123** [comment]
same problem here with 1.20.4
