### ISSUE TITLE
Banner error

### ISSUE THREAD

**Issue by bobhenl** [LOOHP/InteractiveChat-DiscordSRV-Addon#58]
Hello, I'm getting this error:
```yml
09:24:06 INFO]: Munnies RAPPSIYTB has made the advancement [Not Today, Thank You]
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.loohp.interactivechatdiscordsrvaddon.graphics.BannerGraphics.bannerMetaGetBaseColorMethod" is null
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.BannerGraphics.generateShieldAssets(BannerGraphics.java:134)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.utils.ItemRenderUtils.processItemForRendering(ItemRenderUtils.java:162)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getRawItemImage(ImageGeneration.java:811)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getSingleRawItemImage(ImageGeneration.java:795)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getSingleRawItemImage(ImageGeneration.java:791)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getAdvancementIcon(ImageGeneration.java:221)
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents.onAdvancement(OutboundToDiscordEvents.java:740)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344)
        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:149)
        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.listeners.PlayerAdvancementDoneListener.runAsync(PlayerAdvancementDoneListener.java:103)
        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.listeners.PlayerAdvancementDoneListener.lambda$onPlayerAdvancementDone$0(PlayerAdvancementDoneListener.java:86)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by VincentX0905** [comment]
same
```
[18:49:34 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.loohp.interactivechatdiscordsrvaddon.graphics.BannerGraphics.bannerMetaGetBaseColorMethod" is null
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.BannerGraphics.generateShieldAssets(BannerGraphics.java:134)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.utils.ItemRenderUtils.processItemForRendering(ItemRenderUtils.java:162)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getRawItemImage(ImageGeneration.java:811)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getSingleRawItemImage(ImageGeneration.java:795)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getSingleRawItemImage(ImageGeneration.java:791)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getPlayerInventoryImage(ImageGeneration.java:438)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.graphics.ImageGeneration.getPlayerInventoryImage(ImageGeneration.java:321)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.utils.DiscordContentUtils.createContents(DiscordContentUtils.java:228)
[18:49:34 WARN]:        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.onSlashCommand(DiscordCommands.java:1023)
[18:49:34 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:49:34 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.api.ApiManager.handleSlashCommandEvent(ApiManager.java:319)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.api.ApiManager.onSlashCommand(ApiManager.java:293)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[18:49:34 WARN]:        at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```
