### ISSUE TITLE
Hangs on boot

### ISSUE THREAD

**Issue by joex92** [LOOHP/InteractiveChat-DiscordSRV-Addon#6]
using latest dev-build (4.0.0.14) It just hangs on boot... I tried deleting the plugin's folder and it hangs at `Loading textures...`
Sometimes it fixes by doing a force restart, but there's no other message, no error or warn console message...
when I force a restart I get some errors about command sync, but then in one of those force restarts I got this error:
```
25.06 12:16:11 [Server] INFO Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
25.06 12:16:11 [Server] INFO +> [ScriptEvent] Processed 0 script event paths. 
25.06 12:16:11 [Server] INFO ERROR!
25.06 12:16:11 [Server] INFO Error Message: Failed to synchronize server commands. 
25.06 12:16:11 [Server] INFO ERROR!
25.06 12:16:11 [Server] INFO Error Message: Failed to synchronize server commands. 
25.06 12:16:11 [Server] INFO +> [] +-------------------------+ 
25.06 12:16:11 [Server] WARN java.lang.ThreadDeath
25.06 12:16:11 [Server] WARN at java.base/java.lang.Thread.stop(Thread.java:942)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:887)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:766)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:858)
25.06 12:16:11 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28)
25.06 12:16:11 [Server] INFO Unable to load font provider 1
25.06 12:16:11 [Server] WARN java.awt.FontFormatException: Unexpected runtime exception.
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.TrueTypeFont.<init>(TrueTypeFont.java:228)
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.TrueTypeFont.<init>(TrueTypeFont.java:199)
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2356)
25.06 12:16:11 [Server] WARN at java.desktop/java.awt.Font.<init>(Font.java:621)
25.06 12:16:11 [Server] WARN at java.desktop/java.awt.Font.createFont(Font.java:1225)
25.06 12:16:11 [Server] WARN at com.loohp.interactivechatdiscordsrvaddon.graphics.MCFont.reloadFonts(MCFont.java:68)
25.06 12:16:11 [Server] WARN at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$reloadTextures$0(InteractiveChatDiscordSrvAddon.java:659)
25.06 12:16:11 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
25.06 12:16:11 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1080)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
25.06 12:16:11 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
25.06 12:16:11 [Server] INFO Unable to load font provider 2
25.06 12:16:11 [Server] WARN java.awt.FontFormatException: Unexpected runtime exception.
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.TrueTypeFont.<init>(TrueTypeFont.java:228)
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.TrueTypeFont.<init>(TrueTypeFont.java:199)
25.06 12:16:11 [Server] WARN at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2356)
25.06 12:16:11 [Server] WARN at java.desktop/java.awt.Font.<init>(Font.java:621)
25.06 12:16:11 [Server] WARN at java.desktop/java.awt.Font.createFont(Font.java:1225)
25.06 12:16:11 [Server] WARN at com.loohp.interactivechatdiscordsrvaddon.graphics.MCFont.reloadFonts(MCFont.java:68)
25.06 12:16:11 [Server] WARN at com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$reloadTextures$0(InteractiveChatDiscordSrvAddon.java:659)
25.06 12:16:11 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
25.06 12:16:11 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1080)
25.06 12:16:11 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
25.06 12:16:11 [Server] Startup Done (499.269s)! For help, type "help"
25.06 12:16:12 [Multicraft] Skipped 58 lines due to rate limit (40/s)
```

**Comment by LOOHP** [comment]
You might want to take a look at the Q&A section here: https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/

**Comment by joex92** [comment]
wait.. I'm going to close it for now, I just restarted the server without the plugin and I still got the problem...
it just so happened that this plugin was the last plugin loading at the time of the error...
