### ISSUE TITLE
doesnt work on 1.21.1?

### ISSUE THREAD

**Issue by VipelyRS** [LOOHP/InteractiveChat-DiscordSRV-Addon#65]
[16:00:45 WARN]: [InteractiveChatDiscordSRVAddon] Plugin InteractiveChatDiscordSrvAddon v4.2.12.0 generated an exception while executing task 36
java.lang.RuntimeException: No NMSWrapper implementation for UNSUPPORTED version UNSUPPORTED
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar/com.loohp.interactivechatdiscordsrvaddon.nms.NMSAddon.getInstance(NMSAddon.java:46) ~[InteractiveChatDiscordSrvAddon-4.2.12.0.jar:?]
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar/com.loohp.interactivechatdiscordsrvaddon.utils.ResourcePackUtils.getServerResourcePack(ResourcePackUtils.java:28) ~[InteractiveChatDiscordSrvAddon-4.2.12.0.jar:?]
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar/com.loohp.interactivechatdiscordsrvaddon.AssetsDownloader.downloadServerResourcePack(AssetsDownloader.java:186) ~[InteractiveChatDiscordSrvAddon-4.2.12.0.jar:?]
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar/com.loohp.interactivechatdiscordsrvaddon.InteractiveChatDiscordSrvAddon.lambda$reloadTextures$17(InteractiveChatDiscordSrvAddon.java:681) ~[InteractiveChatDiscordSrvAddon-4.2.12.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.loohp.interactivechatdiscordsrvaddon.nms.UNSUPPORTED
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at InteractiveChatDiscordSrvAddon-4.2.12.0.jar/com.loohp.interactivechatdiscordsrvaddon.nms.NMSAddon.getInstance(NMSAddon.java:38) ~[InteractiveChatDiscordSrvAddon-4.2.12.0.jar:?]
        ... 9 more

**Comment by LOOHP** [comment]
You are not running the latest version.
