### ISSUE TITLE
can't make chat sync from discord to the server

### ISSUE THREAD

**Issue by NOBODY7478** [LOOHP/InteractiveChat-DiscordSRV-Addon#67]
I gey this when the server starts:

! [Fri 00:37:51 WARN ] Exception in thread "DiscordSRV - Channel Topic Updater" java.lang.NoClassDefFoundError: Could not initialize class github.scarsz.discordsrv.util.PlayerUtil
! [Fri 00:37:51 WARN ]     at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replaceChannelUpdaterPlaceholders(PlaceholderUtil.java:91)
! [Fri 00:37:51 WARN ]     at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:44)
! [Fri 00:37:51 WARN ] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "DiscordSRV - Presence Updater"]
! [Fri 00:37:51 WARN ]     at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.util.PlayerUtil.<clinit>(PlayerUtil.java:79)
! [Fri 00:37:51 WARN ]     at DiscordSRV-Build-1.28.0.jar//github.scarsz.discordsrv.objects.threads.PresenceUpdater.run(PresenceUpdater.java:77)
  [Fri 00:37:52 INFO  DiscordSRV] Cleared all pre-existing slash commands in 1/1 guilds (0 cancelled)

**Comment by NOBODY7478** [comment]
i found the problem, the spigot page didn't have the latest version so i had to download it from github
