### ISSUE TITLE
String containing sender UUID being displayed in game during chat.

### ISSUE THREAD

**Issue by A-N-I-K** [LOOHP/InteractiveChat-DiscordSRV-Addon#8]
Whenever a user sends an in-game chat, the chat window shows their message, followed by the string '<chat={Player UUID}>'. However, the message is properly (i.e. without additional strings) displayed on Discord.

Server: paper-1.17.1-255

===============
DURING SERVER START
===============

[18:09:27 ERROR]: [DiscordSRV] DiscordSRV API Listener com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents threw an error
[18:09:27 ERROR]: [DiscordSRV] java.lang.NoSuchMethodError: 'github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction github.scarsz.discordsrv.dependencies.jda.api.entities.Guild.retrieveCommands()'
[18:09:27 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.3.11.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.reload(DiscordCommands.java:86)
[18:09:27 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.3.11.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordCommands.<init>(DiscordCommands.java:77)
[18:09:27 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.3.11.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.ready(DiscordReadyEvents.java:45)
[18:09:27 ERROR]: [DiscordSRV]  at InteractiveChatDiscordSrvAddon-4.0.3.11.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.DiscordReadyEvents.onDiscordReady(DiscordReadyEvents.java:35)
[18:09:27 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:09:27 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:09:27 ERROR]: [DiscordSRV]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:09:27 ERROR]: [DiscordSRV]  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:09:27 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:134)
[18:09:27 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:1328)
[18:09:27 ERROR]: [DiscordSRV]  at java.base/java.lang.Thread.run(Thread.java:831)

==============
DURING CHAT EVENT
==============

[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: java.lang.NoSuchFieldException: ping
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:88)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:61)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:296)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:89)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:72)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:96)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:76)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:264)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:62)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$0(OutChatPacket.java:126)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.getInt(Object)" because "this.ping" is null
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:71)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:296)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse0(PlaceholderParser.java:89)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.utils.PlaceholderParser.parse(PlaceholderParser.java:72)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.modules.PlayernameDisplay.processPlayer(PlayernameDisplay.java:96)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:76)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:264)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:62)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at InteractiveChat-4.0.3.13.jar//com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$0(OutChatPacket.java:126)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:18:29] [InteractiveChat Async ChatMessage Processing Thread #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:19:23] [JDA MainWS-ReadThread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.interactivechatdiscordsrvaddon.listeners.InboundToGameEvents.discordRegexesField" is null
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at InteractiveChatDiscordSrvAddon-4.0.3.11.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.InboundToGameEvents.onRecieveMessageFromDiscordPre(InboundToGameEvents.java:89)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:134)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:119)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:445)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:151)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[18:19:23] [JDA MainWS-ReadThread/WARN]: 	at DiscordSRV-Build-1.23.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by LOOHP** [comment]
You need to update your plugins:
PlaceholderAPI -> latest release
And then update the player expansion (/papi ecloud download player)
DiscordSRV -> 1.24.0-SNAPSHOT
And then grant slash command access to your bot
https://stackoverflow.com/questions/65539808/missing-access-for-slash-commands
https://i.imgur.com/S0KqHUe.png

**Comment by A-N-I-K** [comment]
- Deleting the PlaceholderAPI folder and updating the player expansion as you suggested fixed the chat related errors.
- Updating DiscordSRV from 1.23.0 -> 1.24.0-SNAPSHOT-bd18f24 fixed the errors during server startup.

Thank you so much for your quick and detailed response! This issue is now resolved.
