### ISSUE TITLE
Console Error Log

### ISSUE THREAD

**Issue by RocketManKian** [LOOHP/InteractiveChat-DiscordSRV-Addon#9]
I updated to the latest InteractiveChat Version and DiscordSRV Version and now everytime a player types this is spammed in the console.

`[23:28:25 ERROR]: [DiscordSRV] java.lang.NoSuchFieldError: placeholderList
[23:28:25 ERROR]: [DiscordSRV] DiscordSRV API Listener com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents threw an error
[23:28:25 ERROR]: [DiscordSRV] at InteractiveChatDiscordSrvAddon-4.0.3.4.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents.onGameToDiscord(OutboundToDiscordEvents.java:155)
[23:28:25 ERROR]: [DiscordSRV] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:28:25 ERROR]: [DiscordSRV] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[23:28:25 ERROR]: [DiscordSRV] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[23:28:25 ERROR]: [DiscordSRV] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:28:25 ERROR]: [DiscordSRV] at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1667)
[23:28:25 ERROR]: [DiscordSRV] at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:136)
[23:28:25 ERROR]: [DiscordSRV] at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1611)
[23:28:25 ERROR]: [DiscordSRV] at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.listeners.PlayerChatListener.lambda$onAsyncPlayerChat$0(PlayerChatListener.java:43)
[23:28:25 ERROR]: [DiscordSRV] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:28:25 ERROR]: [DiscordSRV] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:28:25 ERROR]: [DiscordSRV] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:28:25 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:28:25 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:28:25 ERROR]: [DiscordSRV] at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by LOOHP** [comment]
Did DiscordSRV start properly?

**Comment by RocketManKian** [comment]
It did yep. So the fix was me trying out the Development Version rather than Stable Release Version and it got fixed, so thank you :)
